config/routes.rb
Rails.application.routes.draw do
  resources :imported_protocols
  post 'jsons/save' => 'imported_protocols/save', :as => :save
  resources :jsons
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/imported_protocol.rb
class ImportedProtocol < ApplicationRecord
end

app/models/json.rb
class Json < ApplicationRecord
  require 'json'
  # app/models/document.rb
  #attr_reader :p_vendor_link
#  attr_reader :protocol_name
  #attr_reader :p_last_modified
  #attr_reader :p_description_link
#  attr_reader :p_number_of_steps
  #attr_reader :p_uri
  attr_accessor :filename
  attr_accessor :content_type
  attr_accessor :file_contents
  attr_accessor :objekt
  attr_accessor :file

def initialize(params = {})
#byebug
super
if( params.has_key?(:content_type) && params.has_key?(:file_contents)&&params.has_key?(:objekt))

  self.filename=params.delete(:filename)
  self.content_type=params.delete(:content_type)
  self.file_contents=params.delete(:file_contents).to_i(2)
  self.objekt=params.delete(:objekt).to_i(2)

  byebug
else
 @file = params.delete(:file)

  #byebug
 #super
  if @file

    @filename = sanitize_filename(@file.original_filename)
    @content_type = @file.content_type
    @file_contents = @file.read
    @objekt=JSON.parse(@file_contents)
    #byebug
    #attr_reader :ime_protokola
    #ime_protokola=objekt["protocol_name"]
    #ustvari(parsan_tekst)
    #@p_vendor_link=@objekt["vendor_link"]
    #byebug
    #@protocol_name=@objekt["protocol_name"]
    #@p_last_modified=@objekt["last_modified"]
    #@p_description_link=@objekt["link"]
    #@p_number_of_steps=o@bjekt["number_of_steps"]
    #@p_uri=objekt["uri"]


  end
end
end
#def ustvari(objekt)

#end

private
  def sanitize_filename(filename)
    # Get only the filename, not the whole path (for IE)
    # Thanks to this article I just found for the tip: http://mattberther.com/2007/10/19/uploading-files-to-a-database-using-rails
    return File.basename(filename)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


end

app/controllers/imported_protocols_controller.rb
class ImportedProtocolsController < ApplicationController
  before_action :set_imported_protocol, only: [:show, :edit, :update, :destroy]

  # GET /imported_protocols
  # GET /imported_protocols.json
  def index
    @imported_protocols = ImportedProtocol.all
  end

  # GET /imported_protocols/1
  # GET /imported_protocols/1.json
  def show
  end
  def create

  end
  # GET /imported_protocols/new
  def new
    @imported_protocol = ImportedProtocol.new
  end

  # GET /imported_protocols/1/edit
  def edit
  end

  # POST /imported_protocols
  # POST /imported_protocols.json
  def save
    @imported_protocol = ImportedProtocol.new(imported_protocol_params)

    respond_to do |format|
      if @imported_protocol.save
        format.html { redirect_to :action => "index" }
        format.json { redirect_to :action => "index"}
      else
        format.html { render :new }
        format.json { render json: @imported_protocol.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /imported_protocols/1
  # PATCH/PUT /imported_protocols/1.json
  def update
    respond_to do |format|
      if @imported_protocol.update(imported_protocol_params)
        format.html { redirect_to @imported_protocol, notice: 'Imported protocol was successfully updated.' }
        format.json { render :show, status: :ok, location: @imported_protocol }
      else
        format.html { render :edit }
        format.json { render json: @imported_protocol.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /imported_protocols/1
  # DELETE /imported_protocols/1.json
  def destroy
    @imported_protocol.destroy
    respond_to do |format|
      format.html { redirect_to imported_protocols_url, notice: 'Imported protocol was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_imported_protocol
      @imported_protocol = ImportedProtocol.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def imported_protocol_params
      params.fetch(:imported_protocol, {})
    end
end

app/controllers/jsons_controller.rb
class JsonsController < ApplicationController

  before_action :set_json, only: [:show, :edit, :update, :destroy]

  # GET /jsons
  # GET /jsons.json
  def index
    @jsons = Json.all


  end

  # GET /jsons/1
  # GET /jsons/1.json
  def show
    respond_to do |format|
    format.html
    format.js
  end
  #send_data(@json.file_contents,
          #  type: @json.content_type,
          #  filename: @json.filename)
  end

  # GET /jsons/new
  def new
    @json = Json.new

  end

  # GET /jsons/1/edit
  def edit
  end

  def save

    @json=Json.new(json_params)
    byebug
    #@json.filename=params["json"]["filename"]
    #@json.content_type=params["json"]["content_type"]
    #@json.file_contents=params["json"]["file_contents"]
    #@json.objekt=params["json"]["objekt"]
    respond_to do |format|
      if @json.save
      format.html { redirect_to :action => "index"}
      format.json { redirect_to :action => "index" }
      else
      format.html { render :new }
      format.json { render json: @json.errors, status: :unprocessable_entity }
      end
    end
  end
  # POST /jsons
  # POST /jsons.json
  def create

    @json = Json.new(json_params)
    #byebug
    respond_to do |format|
      format.html { render :show, notice: 'Json was successfully created.'}
      format.json { render :show, status: :created, location: @json }
    end

    # , :remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window'


  end

  # PATCH/PUT /jsons/1
  # PATCH/PUT /jsons/1.json
  def update
    respond_to do |format|
      if @json.update(json_params)
        format.html { redirect_to @json, notice: 'Json was successfully updated.' }
        format.json { render :show, status: :ok, location: @json }
      else
        format.html { render :edit }
        format.json { render json: @json.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jsons/1
  # DELETE /jsons/1.json
  def destroy
    @json.destroy
    respond_to do |format|
      format.html { redirect_to jsons_url, notice: 'Json was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_json
      @json = Json.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def json_params
      params.require(:json).permit(:file1,:file,:filename,:filename1,:content_type1,:content_type,:file_contents,:file_contents1,:objekt,:objekt1)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/imported_protocols_helper.rb
module ImportedProtocolsHelper
end

app/helpers/jsons_helper.rb
module JsonsHelper
end

app/views/imported_protocols/_form.html.erb
<%= form_with(model: imported_protocol, local: true) do |form| %>
  <% if imported_protocol.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(imported_protocol.errors.count, "error") %> prohibited this imported_protocol from being saved:</h2>

      <ul>
      <% imported_protocol.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/imported_protocols/edit.html.erb
<h1>Editing Imported Protocol</h1>

<%= render 'form', imported_protocol: @imported_protocol %>

<%= link_to 'Show', @imported_protocol %> |
<%= link_to 'Back', imported_protocols_path %>

app/views/imported_protocols/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Imported Protocols</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @imported_protocols.each do |imported_protocol| %>
      <tr>
        <td><%= link_to 'Show', imported_protocol %></td>
        <td><%= link_to 'Edit', edit_imported_protocol_path(imported_protocol) %></td>
        <td><%= link_to 'Destroy', imported_protocol, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Imported Protocol', new_imported_protocol_path %>

app/views/imported_protocols/new.html.erb
<h1>New Imported Protocol</h1>

<%= render 'form', imported_protocol: @imported_protocol %>

<%= link_to 'Back', imported_protocols_path %>

app/views/imported_protocols/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_imported_protocol_path(@imported_protocol) %> |
<%= link_to 'Back', imported_protocols_path %>

app/views/jsons/_form.html.erb
<%= form_for(@json) do |f| %>
  <div class="field">
    <%= f.file_field :file , {:onchange => 'this.form.submit()' } %>

  </div>
  <div class="actions">
    <% # f.submit %>
  </div>
<% end %>

app/views/jsons/edit.html.erb
<h1>Editing Json</h1>

<%= render 'form', json: @json %>

<%= link_to 'Show', @json %> |
<%= link_to 'Back', jsons_path %>

app/views/jsons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jsons</h1>

<table>
  <thead>
    <tr>
      <th>Filename</th>
      <th>Content type</th>
      <th>File contents</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jsons.each do |json| %>
      <tr>
        <td><%= json.filename %></td>
        <td><%= json.content_type %></td>
        <td><%# json.file_contents %></td>
        <td><%= link_to 'Show', json %></td>
        <td><%= link_to 'Edit', edit_json_path(json) %></td>
        <td><%= link_to 'Destroy', json, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Json', new_json_path %>

app/views/jsons/new.html.erb
<h1>New Json</h1>

<%= render 'form', json: @json %>

<%= link_to 'Back', jsons_path %>

app/views/jsons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Filename:</strong>
  <%= @json.filename %>
</p>

<p>
  <strong>Content type:</strong>
  <%= @json.content_type %>
</p>

<p>
  <strong>File contents:</strong>
  <% #@json.file_contents %>
</p>






<% if false %>
<% #da error ker ni še tega objekta v bazi %>
<% link_to 'Edit', edit_json_path(@json) %> |
<% link_to 'Back', jsons_path %>
<% end %>
<% #if false %>


<a type="button" class="btn" style="width:100%;height:100%;" href="#test_modal" data-toggle="modal">odpri modalca</a>

<div class="modal fade" style="width:9%;margin-left:5%;margin-right:5;" id="test_modal" >
  <div class="modal-header" style="width:90%;margin-left:5%;margin-right:5%;">
    <a class="close" data-dismiss="modal">&times;</a>
    <h3>Uploading protocols.io File</h3>
    <h5>Below you can review the data which will get imported</h5>
  </div>
  <div class="modal-body" style="width:90%;margin-left:5%;margin-right:5%;"  >
    <style>
    tr:hover{background-color:#f5f5f5}
    td {padding-bottom: 10px;padding-top:10px;}


    </style>
    <table>
      <tr>
        <th>Description</th>
        <th>Value</th>
        <th>Notes</th>
      </tr>

      <tr>
        <td> Protocol name</td>
        <td> <%= @json.objekt["protocol_name"] %></td>
        <td> WIP</td>
      </tr>
      <tr>
        <td> Number of steps </td>
        <td> <%= @json.objekt["number_of_steps"] %></td>
        <td> WIP</td>
      </tr>
      <tr>
        <td> Description of protocol </td>
        <td> <%= @json.objekt["description"] %></td>
        <td> WIP</td>
      </tr>
      <tr>
        <td>  Manuscript citation </td>
        <td> <%= @json.objekt["manuscript_citation"] %></td>
        <td> WIP</td>
      </tr>
      <tr>
        <td>  Protocol picture (Protocols.io) </td>
        <td> <%= @json.objekt["big_protocol_img"] %></td>
        <td> WIP</td>
      </tr>

      <% counter=0
      whitelist_simple=["1","6","17"]
      whitelist_complex=["8","9","15","18","19","20"]%>
      <% #byebug %>
<% @json.objekt["steps"].each do |step| %>
      <tr>
        <td> Step <%= (counter+=1).to_s %> </td>
        <td> Step guid (Protocols.io) :<%= step["guid"] %>
          <% #byebug %>
          <% if counter>1 %>
          <br>Guid of previous step (Protocols.io) :<%= step["previous_guid"] %>
           <% end  #counter, prvi step nima previous guid%>
  <% step["components"].each do |key,value|  %>
          <% #byebug %>

      <% if counter>1 #nevem zaka ampak v vseh njihovih izvoženih jsonih ima prvi korak čudno strukturo
          #elementov, v kateri so shranjeni kot hash, katerega ključ je "0", vrednost pa komponenta, to zruši iteriranje v enem stavku
          #trenutno sem porabil {5} ur da bi našel rešitev, tako da bi ena zanka naredila oboje.
          # to je samo v  prvem koraku, naprej so vsi shranjeni brez tega arraya, in se po njih da normalno iterirat
          %>
          <% #byebug %>
          <% if whitelist_simple.include?(key["component_type_id"]) && key["data"]!="" && key["name"] && key["data"]%>
          <br>
          <%= key["name"]+" : "+key["data"] %>
          <% #byebug
          #debug
          #comp[counter];counter;@json.file_contents["steps"][3]["components"][0]["name"]
          #@json.file_contents["steps"][0]["components"]
          %>

          <% elsif key && whitelist_complex.include?(key["component_type_id"]) %>
          <% case key["component_type_id"]%>
          <% when "8"%>
          <br>
          <%= "-"+key["name"]+" : "+key["source_data"]["name"] %>
          <br>
          Developer : <%= key["source_data"]["developer"] %>
          <br>
          Version : <%= key["source_data"]["version"] %>
          <br>
          Link : <%= key["source_data"]["link"] %>
          <br>
          Repository : <%= key["source_data"]["repository"] %>
          <br>
          OS name , OS version : <%= key["source_data"]["os_name"]+" , "+key["source_data"]["os_version"] %>

          <% when "9"%>
          <br>
          <%= "-"+key["name"]+" : "+key["source_data"]["name"] %>
          <br>
          Link : <%= key["source_data"]["link"] %>


          <% when "15"%>
          <br>
          <%= "-"+key["name"]+" : "+key["source_data"]["name"] %>
          <br>
          Description : <%= key["source_data"]["description"] %>
          <br>
          OS name , OS version : <%= key["source_data"]["os_name"]+" , "+key["source_data"]["os_version"] %>

          <% when "18"%>

          <% when "19"%>
          <br>
          <%= "-"+key["name"]+" : "+key["source_data"]["body"] %>
          <br>
          Link : <%= key["source_data"]["link"] %>


          <% when "20"%>

          <% else %>

          <% end %>


          <% end #notranji if št 1%>


      <% else %>
        <% unless value %>
        <% value=key #json format ima random arraye namest hashov, ta problem je opisan pri if counter > 1 stavku %>
        <% end %>
          <% if whitelist_simple.include?(value["component_type_id"])&& value["data"]!="" && value["name"] && value["data"]  %>
          <br>
          <%= value["name"]+" : "+value["data"] %>
          <% #byebug
          #debug
          #comp[counter];counter;@json.file_contents["steps"][3]["components"][0]["name"]
          #@json.file_contents["steps"][0]["components"]
          %>

          <% elsif value && whitelist_complex.include?(value["component_type_id"]) %>
          <% case value["component_type_id"]%>
          <% when "8"%>
          <br>
          <%= "-"+value["name"]+" : "+value["source_data"]["name"] %>
          <br>
          Developer : <%= value["source_data"]["developer"] %>
          <br>
          Version : <%= value["source_data"]["version"] %>
          <br>
          Link : <%= value["source_data"]["link"] %>
          <br>
          Repository : <%= value["source_data"]["repository"] %>
          <br>
          OS name , OS version : <%= value["source_data"]["os_name"]+" , "+value["source_data"]["os_version"] %>

          <% when "9"%>
          <br>
          <%= "-"+value["name"]+" : "+value["source_data"]["name"] %>
          <br>
          Link : <%= value["source_data"]["link"] %>


          <% when "15"%>
          <br>
          <%= "-"+value["name"]+" : "+value["source_data"]["name"] %>
          <br>
          Description : <%= value["source_data"]["description"] %>
          <br>
          OS name , OS version : <%= value["source_data"]["os_name"]+" , "+value["source_data"]["os_version"] %>

          <% when "18"%>

          <% when "19"%>
          <br>
          <%= "-"+value["name"]+" : "+value["source_data"]["body"] %>
          <br>
          Link : <%= value["source_data"]["link"] %>


          <% when "20"%>

          <% else %>

          <% end %>

          <% end #notranji if št 2%>

      <% end #zunanji if %>


  <% end #komponente koraka %>
        </td>
        <td> WIP</td>
      </tr>
<% end  #posamezni koraki%>



      <tr>
        <td> Authors </td>
        <td> <%= @json.objekt["authors"] %></td>
        <td> WIP</td>
      </tr>
      <tr>
        <td> Protocol link </td>
        <td> <%= @json.objekt["link"] %></td>
        <td> WIP</td>
      </tr>
      <tr>
        <td> Id of protocol (protocols.io) </td>
        <td> <%= @json.objekt["protocol_id"] %></td>
        <td> WIP</td>
      </tr>


      <tr>
        <td> Before start protocol information (protocols.io) </td>
        <td> <%= @json.objekt["before_start"] %></td>
        <td> WIP</td>
      </tr>
      <tr>
        <td> Username of author (protocols.io) </td>
        <td> <%= @json.objekt["username"] %></td>
        <td> WIP</td>
      </tr>
      <tr>
        <td> Uri of protocol (protocols.io) </td>
        <td> <%= @json.objekt["uri"] %></td>
        <td> WIP</td>
      </tr>
      <tr>
        <td> Vendor name (Protocols.io) </td>
        <td> <%= @json.objekt["vendor_name"] %></td>
        <td> WIP</td>
      </tr>
      <tr>
        <td> Vendor link (Protocols.io) </td>
        <td> <%= @json.objekt["vendor_link"] %></td>
        <td> WIP</td>
      </tr>
      <tr>
        <td> Vendor logo (Protocols.io) </td>
        <td> <%= @json.objekt["vendor_logo"] %></td>
        <td> WIP</td>
      </tr>
      <tr>
        <td> Warning (protocols.io)</td>
        <td> <%= @json.objekt["warning"] %></td>
        <td> WIP</td>
      </tr>
      <tr>
        <td> Guidelines (Protocols.io) </td>
        <td> <%= @json.objekt["guidelines"] %></td>
        <td> WIP</td>
      </tr>
      <tr>
        <td> Doi ?? (protocols.io)</td>
        <td> <%= @json.objekt["doi"] %></td>
        <td> WIP</td>
      </tr>
      <tr>
        <td> Private link (Protocols.io)  </td>
        <td> <%= @json.objekt["private_link"] %></td>
        <td> WIP</td>
      </tr>
      <tr>
        <td> Protocol keywords (Protocols.io) </td>
        <td> <%= @json.objekt["keywords"] %></td>
        <td> WIP</td>
      </tr>
      <tr>
        <td> Last modified date (Protocols.io)  </td>
        <td> <%= @json.objekt["last_modified"] %></td>
        <td> WIP</td>
      </tr>
      <tr>
        <td> Created on date (Protocols.io) </td>
        <td> <%= @json.objekt["created_on"] %></td>
        <td> WIP</td>
      </tr>
      <tr>
        <td> First published date (Protocols.io) </td>
        <td> <%= @json.objekt["first_published_date"] %></td>
        <td> WIP</td>
      </tr>
      <tr>
        <td> Publish date (Protocols.io) </td>
        <td> <%= @json.objekt["publish_date"] %></td>
        <td> WIP</td>
      </tr>
      <tr>
        <td> Tags (Protocols.io) </td>
        <td> <% @json.objekt["tags"].each do |tag| %>
          <%= tag["tag_name"]+" , "%>
          <% end %>


        </td>
        <td> WIP</td>
      </tr>



    </table>
    <% if false  %>
    <% @json.objekt.each do |key,value| %>
    <tr>
      <td><%= key %></td>
      <td><%= value %></td>
      <td>WIP</td>
    </tr>
    <% end %>
    <% end %>
<%# @json.file_contents.key?("kljuc") %>
  </div>
  <div class="modal-footer" style="width:90%;margin-left:5%;margin-right:5%;">
    <%= link_to "Discard protocol", new_json_path, class: "btn"%>
    <% # <a href="#" class="btn" data-dismiss="modal">Discard protocol</a> # %>

    <%= form_for @json, :url => {:action=>"save", :controller=>"jsons"},:html => { :method => "POST"} do |f| %>
    <%=f.hidden_field :filename, :value => @json.filename%>
    <%=f.hidden_field :content_type, :value => @json.content_type%>
    <%=f.hidden_field :file_contents, :value => @json.file_contents%>
    <%= f.hidden_field :objekt, :value => @json.objekt%>
    <%#f.hidden_field :file, :value => @json.file%>
    <% #byebug %>
  <%= f.submit 'Import protocol', class: "btn btn-primary"%>
<% end %>
    <%#link_to "Import protocol",save_path(:testiranje => "ll"), class: "btn btn-primary", method: :post%>
    <% #byebug#<a href="#" class="btn btn-primary">Import protocol</a> %>
  </div>
</div>
<script type="text/javascript">
    $(document).ready(function(){
        $('#test_modal').modal('show');
    });
</script>
<% if false %>
<script type="text/javascript">
$('#test_modal').modal('hide')
</script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JsonUpload</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>

  

  </body>
</html>